lib/poster_app_web/router.ex
defmodule PosterAppWeb.Router do
  use PosterAppWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {PosterAppWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :auth do
    plug(PosterAppWeb.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :allowed_for_users do
    plug(PosterAppWeb.Plugs.AuthorizationPlug, ["admin", "user"])
  end

  pipeline :allowed_for_admins do
    plug(PosterAppWeb.Plugs.AuthorizationPlug, ["admin"])
  end

  scope "/", PosterAppWeb do
    pipe_through([:browser, :auth])

    get("/", PageController, :index)

    get("/login", SessionController, :new)

    post("/login", SessionController, :login)

    get("/logout", SessionController, :logout)

    get("/users/new", UserController, :new)

    post("/users", UserController, :create)
  end

  scope "/", PosterAppWeb do
    pipe_through([:browser, :auth, :ensure_auth, :allowed_for_users])

    get("/hashtags/search", HashtagController, :index)

    post("/hashtags/search/result", HashtagController, :show)

    get("/posts/new", PostController, :new)

    post("/posts", PostController, :create)

    get("/posts", PostController, :index)

    get("/posts/:post_id/edit", PostController, :edit)

    put("/posts/:post_id", PostController, :update)

    patch("/posts/:post_id", PostController, :update)

    delete("/posts/:post_id", PostController, :delete)

    get("/users", UserController, :index)

    get("/users/:user_id", UserController, :show)

    get("/users/:user_id/edit", UserController, :edit)

    put("/users/:user_id", UserController, :update)

    patch("/users/:user_id", UserController, :update)

    get("/user_scope", PageController, :user_index)

    delete("/posts/delete/:post_id/:comment_id", PostController, :delete_comment)

    get("/posts/:post_id", PostController, :interact)

    get("/posts/add_comment/:post_id", PostController, :add_comment)

    patch("/posts/like/:post_id", PostController, :increase_likes)

    patch("/posts/unlike/:post_id", PostController, :decrease_likes)

    post("/posts/create_comment/:post_id", PostController, :create_comment)

    patch("/users/follow/:user_id", UserController, :follow)

    patch("/users/unfollow/:user_id", UserController, :unfollow)

    delete "/users/:user_id", UserController, :delete
  end

  scope "/admin", PosterAppWeb do
    pipe_through([:browser, :auth, :ensure_auth, :allowed_for_admins])
  end

  # Other scopes may use custom stacks.
  # scope "/api", PosterAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: PosterAppWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end
end

lib/poster_app_web/views/layout_view.ex
defmodule PosterAppWeb.LayoutView do
  use PosterAppWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/poster_app_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/poster_app_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/poster_app_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "PosterApp", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <%= if @user_id != nil do %>
              <li><%= link "Users", to: Routes.user_path(@conn, :index) %></li>
              <li><%= link "Posts", to: Routes.post_path(@conn, :index) %></li>
              <li><%= link "Search", to: Routes.hashtag_path(@conn, :index) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>